version: '3'

# Start with
#     `docker-compose up -d ldm glmtest`

services:
  ###
  # LDM
  ###
  ldm:
    image: ldm-glm
    container_name: ldm-prod
    # image: unidata/ldm-docker:6.13.11
    # restart: always
    volumes:
      # change defaults to your liking
      - ./etc/:/home/ldm/etc/
      - ./data/:/home/ldm/var/data/
      - ./queues:/home/ldm/var/queues/
      - ./logs/:/home/ldm/var/logs/
      - ./cron/:/var/spool/cron/
      # - /archive/GLM/GLM-L2-GRID_G16/:/glm_grid_data
      # - /archive/GLM/GLM-L2-GRIDRELAMPAGO_G16/:/glm_grid_relampago
    ports:
      - "388:388"
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    env_file:
      - "compose.env"
  glm-16:
    image: glmtest
    container_name: glm-16
    volumes:
      - ./data/GLM-L2-LCFA_G16/:/glm_raw_data
      - ./data/GLM-L2-GRID_G16/:/glm_grid_data
      - ./data/GLM-L2-IMGSCONUS_G16/:/glm_plots
    # like run -it, so it stays up
    stdin_open: true
    tty: true  
    entrypoint:
      - /bin/bash
  glm-17:
    image: glmtest
    container_name: glm-17
    volumes:
      - ./data/GLM-L2-LCFA_G17/:/glm_raw_data
      - ./data/GLM-L2-GRID_G17/:/glm_grid_data
      - ./data/GLM-L2-IMGSCONUS_G17/:/glm_plots
    # like run -it, so it stays up
    stdin_open: true
    tty: true  
    entrypoint:
      - /bin/bash
    #   - /home/glm/aws_realtime/run.sh
  # glmrelampago:
  #   image: glmrelampago
  #   container_name: glm-relampago
  #   volumes:
  #     - /archive/GLM/GLM-L2-LCFA_G16:/glm_raw_data
  #     - /archive/GLM/GLM-L2-GRIDRELAMPAGO_G16:/glm_grid_data
  #     - /archive/GLM/GLM-L2-IMGSRELAMPAGO_G16:/glm_plots
  #   # like run -it, so it stays up
  #   stdin_open: true
  #   tty: true
  #   entrypoint:
  #     - /bin/bash
    #   - /home/glm/aws_realtime/run.sh
